"""Geometry Solver foundation: turns an `ArchitecturalSpec` (room types, counts, relationships,
zones, circulation) plus a `BuildingFootprintSpec` — NEVER a `SiteSpec`, see that class's docstring —
into concrete, non-overlapping, in-bounds room instances. Every HARD constraint is enforced exactly;
SOFT relationships/zones/circulation are treated as an objective to maximize among the valid layouts
found, never as something that can silently fail.

Algorithm (bounded backtracking over "corner point" candidate positions, run once per instance-order
strategy and pooled — see Step 3 below):

1. Order instances: the circulation entry room always first; then, per `_INSTANCE_ORDER_STRATEGIES`,
   either by how many HARD relationships its type has (most-constrained-first — the original, default
   CSP ordering heuristic), by largest target area first, or by smallest target area first (both
   standard rectangle-packing heuristics). The search below runs once per strategy.
2. For each instance, generate a small set of candidate (width, height) shapes from
   `target_area_m2` (preference, tried first) and `min_area_m2`/`max_area_m2` (hard bounds, tried as
   fallback areas), each combined with a few fixed aspect ratios, filtered to respect the HARD
   `min_width_m` on both sides.
3. Positions tried are the footprint origin plus every "corner point" generated by already-placed
   rooms (flush against a placed room's right or bottom edge — a standard rectangle-packing
   heuristic).
4. A candidate placement is accepted only if it stays inside the footprint boundary and does not
   overlap any already-placed room; the search backtracks otherwise.
5. Once every instance is placed, the COMPLETE layout is checked against every HARD requirement (see
   `_layout_satisfies_hard_requirements`): relationships, the footprint's `available_area_m2` budget,
   the entry room touching the footprint perimeter, and any zone whose `cohesion_severity="hard"`.
   Failing any of these rejects the complete layout and the search backtracks further. This two-phase
   check (fast per-step feasibility, then mandatory final verification) is what makes the search
   correct.
6. Every complete valid layout found across ALL strategy passes (up to `_MAX_SOLUTIONS` each,
   deduplicated by exact geometry) is pooled and scored by `_score_candidate`: soft relationships
   satisfied + zone cohesion + circulation reach (as before this milestone) PLUS three new, explicitly
   weighted geometric terms — footprint utilization, compactness, and unused-space fragmentation (see
   `app/geometry/quality.py` and the `_WEIGHT_*` constants below). The highest-scoring pooled candidate
   is returned as `GeometrySolverResult(status=satisfied, ...)`, along with the runner-ups' own score
   breakdowns (`candidate_summaries`) so the choice is explainable, not just a single opaque number. If
   no valid layout is found in any pass, `GeometrySolverResult(status=unsatisfiable, ...)` is returned
   instead — the solver never raises for this expected outcome, and never returns a partial layout.

--- V1 approximations, documented explicitly rather than silently assumed ---

**Adjacency vs. direct access**: both come from the same real quantity — `_shared_edge_length`, the
length in meters of the wall segment two rooms actually share. `adjacent` only requires that length to
be positive; `direct_access` requires it to be at least `_DOOR_OPENING_MIN_M` (a standard interior door
width). No door/opening is actually modeled or drawn. Satisfying `direct_access` proves "a door could
plausibly fit in this wall," never that one exists — every `ConstraintCheckResult` for a satisfied
`direct_access` relationship carries a `note` saying exactly this, so nothing downstream mistakes the
proxy for a real opening.

**Zone cohesion**: a zone's soft "compactness" score is the count of same-zone room PAIRS that end up
adjacent — a simple, deterministic proxy for "grouped together," not a measure of enclosure, shared
corridor, or travel distance. A `cohesion_severity="hard"` zone additionally requires its rooms to form
one connected component via adjacency (every room reachable from every other through same-zone
neighbors) — still just a connectivity graph over shared walls, not a verified walkable path.

**Circulation**: `entry_room_type` is enforced as a HARD requirement that at least one instance of
that type touches one of the footprint's ALLOWED entry edges (`BuildingFootprintSpec.
allowed_entry_edges` — all four edges if unset; candidate placement generation offers all four
footprint corners, so any single edge is genuinely reachable) — approximating "could plausibly have a
front door on a permitted side," not a verified accessible approach from a real street/path (which this
codebase has no data for yet; see Feature 03's location-resolution gap). `requires_hallway` does NOT
create or reserve any hallway polygon. Instead, when true, a SOFT "circulation reach" score rewards
every non-entry-type room that is directly adjacent to an entry-room-type instance — a deliberately
crude proxy for "not obviously buried behind another unrelated room," since a real answer requires an
actual circulation graph/path-planning this foundation does not implement. A high reach score does NOT
prove every room is genuinely reachable without crossing another private room; it only makes such
layouts score better than deeply nested alternatives when multiple valid layouts exist.

This is intentionally a real, verifiable constraint search, not a fixed heuristic layout — but it is
still a "foundation." Swapping in a stronger solver (e.g. an ILP/CP-SAT backend, or a real circulation
graph) later only needs to satisfy this module's function signature.

**Pre-solver contradiction check**: before any search starts, `_find_pre_solver_contradiction` looks
for a small, fixed set of deterministic, easy-to-prove-impossible combinations (a HARD adjacency and a
HARD separation on the same type pair; a HARD direct_access and a HARD separation on the same pair; an
inconsistent min/max area on a program item; a min_width_m that exceeds both footprint dimensions; a
room type referenced but missing from the program). Finding one short-circuits straight to
`status=unsatisfiable` with a specific reason, skipping the search entirely. This is deliberately NOT a
general constraint-satisfiability prover — it only catches contradictions cheap and safe to detect
outright; anything subtler still goes through the full backtracking search and may still come back
unsatisfiable there instead.
"""

from dataclasses import dataclass, field

from app.architect.models import (
    ArchitecturalSpec,
    ConstraintKind,
    ConstraintSeverity,
    ProgramItem,
    RelationalConstraint,
    Zone,
)
from app.geometry.instances import expand_program_to_instances
from app.geometry.models import (
    Edge,
    BuildingFootprintSpec,
    ConstraintCheckResult,
    GeometrySolverResult,
    LayoutQualityReport,
    ObjectiveBreakdown,
    RoomInstance,
    SolverStatus,
)
from app.geometry.quality import compute_quality_metrics

_DEFAULT_TARGET_AREA_M2 = 10.0
_DEFAULT_MIN_WIDTH_M = 2.0
# A deliberately small, fixed set of aspect ratios (width:height) tried per room — not a continuous
# search. 1.0 = square-ish; the other two bias wider or deeper while preserving the chosen area.
_ASPECT_RATIOS = (1.0, 1.4, 1 / 1.4)
# Per-ordering-pass solution cap and shared step budget — see `GeometrySolver.solve`'s module docstring
# Step 3 update: the search is run once per entry in `_INSTANCE_ORDER_STRATEGIES` below (a small set of
# well-established bin-packing order heuristics — "largest item first" and "smallest item first" are
# standard, general techniques, not tuned to any one example), and every complete valid layout found
# across all passes is pooled and ranked together. `_MAX_SOLUTIONS` bounds each individual pass, not the
# combined pool, so the effective candidate count is up to `_MAX_SOLUTIONS * len(_INSTANCE_ORDER_STRATEGIES)`.
_MAX_SOLUTIONS = 8
_MAX_BACKTRACK_STEPS = 20_000
_EPSILON = 1e-6

# --- Explicit, named objective weights (Step 3: "do not hide architectural decisions inside arbitrary
# magic numbers without documenting them") ------------------------------------------------------------
#
# `soft_relationships`/`zone_cohesion`/`circulation_reach` keep their pre-existing weight of 1.0 per
# unit — this milestone does not change how much a satisfied soft relationship or zone-cohesion pair is
# worth relative to each other, only ADDS three new geometric terms alongside them. The three new
# weights below were chosen so that, for a typical BuildSmart program (roughly 5-11 rooms), a full swing
# of `utilization_ratio` (0->1) is worth roughly as much as satisfying 2-3 additional soft relationships
# — geometric quality should matter, but must not make the solver indifferent to the relationship/zone
# requirements the Architect Model and authoritative merge actually asked for. These are starting
# values, deliberately conservative, not derived from any single observed layout.
_WEIGHT_UTILIZATION = 3.0
_WEIGHT_COMPACTNESS = 1.5
_WEIGHT_FRAGMENTATION = 1.5
# Standard interior door width (m) — the threshold that separates `direct_access` from plain
# `adjacent`; see the module docstring's "Adjacency vs. direct access" section.
_DOOR_OPENING_MIN_M = 0.9
_DIRECT_ACCESS_PROXY_NOTE = (
    f"Satisfied via the V1 shared-wall-length proxy (>= {_DOOR_OPENING_MIN_M} m) — this confirms a "
    "door could plausibly fit in that wall, NOT that an actual door/opening exists. No opening "
    "geometry is modeled yet."
)


@dataclass
class _PendingInstance:
    id: str
    type: str
    candidate_shapes: list[tuple[float, float]] = field(default_factory=list)


def _candidate_areas(item: ProgramItem) -> list[float]:
    """Target first (a preference, tried first so the search prefers it), then min/max (hard bounds,
    tried as fallback areas) — see `ProgramItem`'s docstring for the target-vs-bounds semantics."""
    areas: list[float] = []
    if item.target_area_m2 is not None:
        areas.append(item.target_area_m2)
    if item.min_area_m2 is not None:
        areas.append(item.min_area_m2)
    if item.max_area_m2 is not None:
        areas.append(item.max_area_m2)
    if not areas:
        areas.append(_DEFAULT_TARGET_AREA_M2)

    deduped: list[float] = []
    seen: set[float] = set()
    for area in areas:
        key = round(area, 6)
        if key not in seen:
            seen.add(key)
            deduped.append(area)
    return deduped


def _candidate_shapes(item: ProgramItem) -> list[tuple[float, float]]:
    min_width = item.min_width_m or _DEFAULT_MIN_WIDTH_M
    shapes: list[tuple[float, float]] = []
    seen: set[tuple[float, float]] = set()

    for area in _candidate_areas(item):
        for aspect in _ASPECT_RATIOS:
            width = (area * aspect) ** 0.5
            height = area / width
            if width + _EPSILON >= min_width and height + _EPSILON >= min_width:
                key = (round(width, 4), round(height, 4))
                if key not in seen:
                    seen.add(key)
                    shapes.append(key)

    if not shapes:
        area = min(_candidate_areas(item))
        shapes.append((round(min_width, 4), round(area / min_width, 4)))

    return shapes


def _overlaps(ax: float, ay: float, aw: float, ah: float, bx: float, by: float, bw: float, bh: float) -> bool:
    return ax < bx + bw - _EPSILON and ax + aw > bx + _EPSILON and ay < by + bh - _EPSILON and ay + ah > by + _EPSILON


def _shared_edge_length(a: RoomInstance, b: RoomInstance) -> float:
    """The length (m) of the wall segment `a` and `b` actually share, or 0.0 if they don't touch at
    all. This single real quantity backs both `adjacent` (length > 0) and `direct_access` (length >=
    a door width) — see the module docstring."""
    vertical_touch = abs((a.x + a.width) - b.x) < _EPSILON or abs((b.x + b.width) - a.x) < _EPSILON
    if vertical_touch:
        overlap = min(a.y + a.height, b.y + b.height) - max(a.y, b.y)
        if overlap > _EPSILON:
            return overlap

    horizontal_touch = abs((a.y + a.height) - b.y) < _EPSILON or abs((b.y + b.height) - a.y) < _EPSILON
    if horizontal_touch:
        overlap = min(a.x + a.width, b.x + b.width) - max(a.x, b.x)
        if overlap > _EPSILON:
            return overlap

    return 0.0


def _rectangle_gap(a: RoomInstance, b: RoomInstance) -> float:
    """Euclidean distance (m) between the two rectangles' nearest points — 0.0 when they touch or
    overlap. Backs `SeparationConstraint`'s `min_distance_m`."""
    dx = max(b.x - (a.x + a.width), a.x - (b.x + b.width), 0.0)
    dy = max(b.y - (a.y + a.height), a.y - (b.y + b.height), 0.0)
    return (dx * dx + dy * dy) ** 0.5


def _candidate_positions(
    placed: list[RoomInstance], footprint: BuildingFootprintSpec, width: float, height: float
) -> list[tuple[float, float]]:
    """Corner points flush against already-placed rooms, PLUS all four footprint-corner alignments
    for the shape currently being tried. The four footprint corners are always included — not only
    when `placed` is empty — so the very first room placed (typically the entry room) can land against
    ANY of the footprint's four edges, not just the north-west corner. Without this, `allowed_entry_edges`
    restricted to south or east could never be satisfiable no matter the room sizes, since the first
    room would only ever have `(0, 0)` to choose from."""
    positions = {
        (0.0, 0.0),
        (round(footprint.width_m - width, 6), 0.0),
        (0.0, round(footprint.depth_m - height, 6)),
        (round(footprint.width_m - width, 6), round(footprint.depth_m - height, 6)),
    }
    for room in placed:
        positions.add((round(room.x + room.width, 6), round(room.y, 6)))
        positions.add((round(room.x, 6), round(room.y + room.height, 6)))
    return sorted(positions)


def _group_by_type(placed: list[RoomInstance]) -> dict[str, list[RoomInstance]]:
    grouped: dict[str, list[RoomInstance]] = {}
    for room in placed:
        grouped.setdefault(room.type, []).append(room)
    return grouped


def _relationship_satisfied(rel: RelationalConstraint, by_type: dict[str, list[RoomInstance]]) -> bool:
    a_list = by_type.get(rel.room_type_a, [])
    b_list = by_type.get(rel.room_type_b, [])

    if rel.kind == ConstraintKind.adjacency:
        return any(_shared_edge_length(a, b) > _EPSILON for a in a_list for b in b_list)
    if rel.kind == ConstraintKind.direct_access:
        return any(_shared_edge_length(a, b) + _EPSILON >= _DOOR_OPENING_MIN_M for a in a_list for b in b_list)
    if rel.kind == ConstraintKind.separation:
        if rel.min_distance_m is not None:
            # Explicit numeric bound: be lenient at the boundary (float-imprecision tolerance) so a
            # gap of e.g. 1.4999999 against a 1.5 requirement isn't spuriously rejected.
            return all(_rectangle_gap(a, b) + _EPSILON >= rel.min_distance_m for a in a_list for b in b_list)
        # Default "must not touch": be strict — a gap of zero (or within epsilon of zero) is a
        # violation, not a pass. This is the opposite tolerance direction from the branch above on
        # purpose: adding epsilon to the *actual* gap instead of the threshold would make a gap of
        # exactly 0 spuriously satisfy the constraint.
        return all(_rectangle_gap(a, b) > _EPSILON for a in a_list for b in b_list)

    raise AssertionError(f"unhandled relationship kind: {rel.kind!r}")  # exhaustive over RelationalConstraint


def _all_hard_relationships_satisfied(spec: ArchitecturalSpec, by_type: dict[str, list[RoomInstance]]) -> bool:
    return all(
        _relationship_satisfied(rel, by_type) for rel in spec.relationships if rel.severity == ConstraintSeverity.hard
    )


def _within_available_area(footprint: BuildingFootprintSpec, placed: list[RoomInstance]) -> bool:
    return sum(room.area_m2 for room in placed) <= footprint.available_area_m2 + _EPSILON


def _touches_edge(room: RoomInstance, footprint: BuildingFootprintSpec, edge: Edge) -> bool:
    if edge == Edge.west:
        return abs(room.x) < _EPSILON
    if edge == Edge.east:
        return abs((room.x + room.width) - footprint.width_m) < _EPSILON
    if edge == Edge.north:
        return abs(room.y) < _EPSILON
    if edge == Edge.south:
        return abs((room.y + room.height) - footprint.depth_m) < _EPSILON
    raise AssertionError(f"unhandled edge: {edge!r}")  # exhaustive over Edge


def _touches_perimeter(room: RoomInstance, footprint: BuildingFootprintSpec) -> bool:
    """True if `room` touches ANY of the footprint's four edges — used for general "is this on the
    boundary at all" checks. The entry-room hard requirement below uses the narrower, allowed-edges-
    aware `_touches_an_allowed_entry_edge` instead."""
    return any(_touches_edge(room, footprint, edge) for edge in Edge)


def _allowed_entry_edges(footprint: BuildingFootprintSpec) -> list[Edge]:
    """`None` (unset) means "no restriction" — preserved for backward compatibility with specs
    written before `allowed_entry_edges` existed; see `BuildingFootprintSpec`'s docstring."""
    return list(footprint.allowed_entry_edges) if footprint.allowed_entry_edges is not None else list(Edge)


def _touches_an_allowed_entry_edge(room: RoomInstance, footprint: BuildingFootprintSpec) -> bool:
    return any(_touches_edge(room, footprint, edge) for edge in _allowed_entry_edges(footprint))


def _entry_room_has_allowed_edge_access(
    spec: ArchitecturalSpec, footprint: BuildingFootprintSpec, by_type: dict[str, list[RoomInstance]]
) -> bool:
    """Vacuously satisfied when `spec.circulation` is `None` — there is no entry-room claim to enforce
    (see `ArchitecturalSpec.circulation`'s docstring: this happens whenever no gateway/adapter had an
    actual basis for one, never a fabricated default)."""
    if spec.circulation is None:
        return True
    entry_instances = by_type.get(spec.circulation.entry_room_type, [])
    return any(_touches_an_allowed_entry_edge(instance, footprint) for instance in entry_instances)


def _zone_instances(zone: Zone, by_type: dict[str, list[RoomInstance]]) -> list[RoomInstance]:
    return [instance for room_type in zone.room_types for instance in by_type.get(room_type, [])]


def _zone_is_connected(zone: Zone, by_type: dict[str, list[RoomInstance]]) -> bool:
    instances = _zone_instances(zone, by_type)
    if len(instances) <= 1:
        return True
    visited = {instances[0].id}
    frontier = [instances[0]]
    while frontier:
        current = frontier.pop()
        for other in instances:
            if other.id in visited:
                continue
            if _shared_edge_length(current, other) > _EPSILON:
                visited.add(other.id)
                frontier.append(other)
    return len(visited) == len(instances)


def _hard_zones_are_connected(spec: ArchitecturalSpec, by_type: dict[str, list[RoomInstance]]) -> bool:
    return all(
        _zone_is_connected(zone, by_type) for zone in spec.zones if zone.cohesion_severity == ConstraintSeverity.hard
    )


def _layout_satisfies_hard_requirements(
    spec: ArchitecturalSpec, footprint: BuildingFootprintSpec, placed: list[RoomInstance]
) -> bool:
    by_type = _group_by_type(placed)
    return (
        _all_hard_relationships_satisfied(spec, by_type)
        and _within_available_area(footprint, placed)
        and _entry_room_has_allowed_edge_access(spec, footprint, by_type)
        and _hard_zones_are_connected(spec, by_type)
    )


def _zone_cohesion_score(spec: ArchitecturalSpec, by_type: dict[str, list[RoomInstance]]) -> float:
    """Count of same-zone room-instance PAIRS that ended up adjacent, summed across every
    `cohesion_severity="soft"` zone — see the module docstring's "Zone cohesion" section."""
    score = 0.0
    for zone in spec.zones:
        if zone.cohesion_severity != ConstraintSeverity.soft:
            continue
        instances = _zone_instances(zone, by_type)
        for i in range(len(instances)):
            for j in range(i + 1, len(instances)):
                if _shared_edge_length(instances[i], instances[j]) > _EPSILON:
                    score += 1.0
    return score


def _circulation_reach_score(spec: ArchitecturalSpec, by_type: dict[str, list[RoomInstance]]) -> float:
    """Count of non-entry-type room instances directly adjacent to an entry-room-type instance —
    only contributes when `circulation.requires_hallway` is true. See the module docstring's
    "Circulation" section for why this is a deliberately crude proxy."""
    if spec.circulation is None or not spec.circulation.requires_hallway:
        return 0.0
    entry_instances = by_type.get(spec.circulation.entry_room_type, [])
    if not entry_instances:
        return 0.0
    score = 0.0
    for room_type, instances in by_type.items():
        if room_type == spec.circulation.entry_room_type:
            continue
        for instance in instances:
            if any(_shared_edge_length(instance, entry) > _EPSILON for entry in entry_instances):
                score += 1.0
    return score


def _score_candidate(
    spec: ArchitecturalSpec, footprint: BuildingFootprintSpec, placed: list[RoomInstance]
) -> tuple[ObjectiveBreakdown, LayoutQualityReport]:
    """The full ranking score for one valid (all-HARD-constraints-satisfied) candidate layout — see the
    module docstring's Step 3 update and `_WEIGHT_*` above for what each term means and why. Returns
    both the score breakdown (for `GeometrySolverResult.objective_breakdown`/`candidate_summaries` —
    Step 3's "the scoring must be explainable" requirement) and the raw geometric quality report (for
    `GeometrySolverResult.quality`) so callers get the underlying numbers, not just the weighted total.
    """
    by_type = _group_by_type(placed)
    soft_relationships = sum(
        1 for rel in spec.relationships if rel.severity == ConstraintSeverity.soft and _relationship_satisfied(rel, by_type)
    )
    zone_score = _zone_cohesion_score(spec, by_type)
    circulation_score = _circulation_reach_score(spec, by_type)
    quality = compute_quality_metrics(spec, footprint, placed, by_type, _shared_edge_length)

    utilization_term = _WEIGHT_UTILIZATION * quality.utilization_ratio
    compactness_term = _WEIGHT_COMPACTNESS * quality.compactness
    fragmentation_term = _WEIGHT_FRAGMENTATION * quality.unused_region_fragmentation_ratio
    total = soft_relationships + zone_score + circulation_score + utilization_term + compactness_term + fragmentation_term

    breakdown = ObjectiveBreakdown(
        soft_relationships_satisfied=float(soft_relationships),
        zone_cohesion_score=zone_score,
        circulation_reach_score=circulation_score,
        utilization_term=round(utilization_term, 4),
        compactness_term=round(compactness_term, 4),
        fragmentation_term=round(fragmentation_term, 4),
        total=round(total, 4),
    )
    quality_report = LayoutQualityReport(
        programmed_area_m2=quality.programmed_area_m2,
        footprint_area_m2=quality.footprint_area_m2,
        utilization_ratio=quality.utilization_ratio,
        unused_area_m2=quality.unused_area_m2,
        largest_contiguous_unused_region_m2=quality.largest_contiguous_unused_region_m2,
        unused_region_fragmentation_ratio=quality.unused_region_fragmentation_ratio,
        compactness=quality.compactness,
        zone_cohesion_ratio=quality.zone_cohesion_ratio,
        circulation_quality_ratio=quality.circulation_quality_ratio,
    )
    return breakdown, quality_report


def _describe(rel: RelationalConstraint) -> str:
    return rel.description or f"{rel.room_type_a} {rel.kind.value} {rel.room_type_b}"


def _relationship_reports(
    spec: ArchitecturalSpec, placed: list[RoomInstance], severity: ConstraintSeverity
) -> list[ConstraintCheckResult]:
    by_type = _group_by_type(placed)
    reports = []
    for rel in spec.relationships:
        if rel.severity != severity:
            continue
        satisfied = _relationship_satisfied(rel, by_type)
        note = _DIRECT_ACCESS_PROXY_NOTE if (rel.kind == ConstraintKind.direct_access and satisfied) else None
        reports.append(
            ConstraintCheckResult(
                description=_describe(rel), kind=rel.kind.value, severity=rel.severity, satisfied=satisfied, note=note
            )
        )
    return reports


# Step 3: a small, well-established set of bin-packing order heuristics — general techniques, not
# tuned to any single observed layout. "most_constrained" is this module's original (pre-this-milestone)
# ordering, kept as the first/default pass so existing behavior is still exactly reproducible as one of
# the pooled candidates, not replaced. "largest_area_first"/"smallest_area_first" are standard rectangle-
# packing heuristics: placing the biggest items first tends to leave more, larger contiguous space for
# the smaller items that follow (and vice versa) — running both alongside the original gives the search
# genuinely different placement orders to explore, which is what lets ranking (Step 3) actually choose
# among meaningfully different layouts instead of near-duplicates of one traversal.
_INSTANCE_ORDER_STRATEGIES = ("most_constrained", "largest_area_first", "smallest_area_first")


def _instance_target_area(item: ProgramItem | None) -> float:
    """ROOM_INSTANCE_SIZE_FIDELITY: takes the SPECIFIC ProgramItem an instance came from (as
    `expand_program_to_instances` already attaches to every instance tuple), never a type-keyed
    re-lookup -- two same-type instances originating from different ProgramItems (e.g. a 14 m2
    bedroom and a 10 m2 bedroom, each its own count=1 item) must resolve to their OWN target, not
    whichever item happens to be last in a `{room_type: item}` dict."""
    if item is None:
        return _DEFAULT_TARGET_AREA_M2
    return item.target_area_m2 or item.min_area_m2 or item.max_area_m2 or _DEFAULT_TARGET_AREA_M2


def _order_instances(
    spec: ArchitecturalSpec,
    instances: list[tuple[str, str, ProgramItem]],
    strategy: str,
) -> list[tuple[str, str, ProgramItem]]:
    hard_relationship_count: dict[str, int] = {}
    for rel in spec.relationships:
        if rel.severity != ConstraintSeverity.hard:
            continue
        hard_relationship_count[rel.room_type_a] = hard_relationship_count.get(rel.room_type_a, 0) + 1
        hard_relationship_count[rel.room_type_b] = hard_relationship_count.get(rel.room_type_b, 0) + 1

    def sort_key(instance: tuple[str, str, ProgramItem]):
        instance_id, room_type, item = instance
        is_entry = spec.circulation is not None and room_type == spec.circulation.entry_room_type
        if strategy == "largest_area_first":
            secondary = -_instance_target_area(item)
        elif strategy == "smallest_area_first":
            secondary = _instance_target_area(item)
        else:
            secondary = -hard_relationship_count.get(room_type, 0)
        return (0 if is_entry else 1, secondary, instance_id)

    return sorted(instances, key=sort_key)


def _unordered_pair(a: str, b: str) -> frozenset[str]:
    return frozenset((a, b))


def _relationship_pairs(spec: ArchitecturalSpec, kind: ConstraintKind, severity: ConstraintSeverity) -> set:
    return {
        _unordered_pair(rel.room_type_a, rel.room_type_b)
        for rel in spec.relationships
        if rel.kind == kind and rel.severity == severity
    }


def _find_pre_solver_contradiction(spec: ArchitecturalSpec, footprint: BuildingFootprintSpec) -> str | None:
    """Deterministic, cheap-to-prove-impossible combinations, checked before any search starts — see
    the module docstring's "Pre-solver contradiction check" section. Deliberately NOT exhaustive: a
    spec that passes here can still come back unsatisfiable from the full search."""
    hard_adjacency_pairs = _relationship_pairs(spec, ConstraintKind.adjacency, ConstraintSeverity.hard)
    hard_direct_access_pairs = _relationship_pairs(spec, ConstraintKind.direct_access, ConstraintSeverity.hard)
    hard_separation_pairs = _relationship_pairs(spec, ConstraintKind.separation, ConstraintSeverity.hard)

    for pair in hard_adjacency_pairs & hard_separation_pairs:
        a, b = sorted(pair)
        return f"{a} and {b} have both a HARD adjacency and a HARD separation requirement — mutually exclusive"

    for pair in hard_direct_access_pairs & hard_separation_pairs:
        a, b = sorted(pair)
        return f"{a} and {b} have both a HARD direct_access and a HARD separation requirement — mutually exclusive"

    for item in spec.program:
        # Redundant with ProgramItem's own model validator (defense in depth at the solver's own
        # entry point, in case a spec ever reaches here without going through that validator).
        if item.min_area_m2 is not None and item.max_area_m2 is not None and item.min_area_m2 > item.max_area_m2:
            return f"{item.room_type}: min_area_m2 ({item.min_area_m2}) exceeds max_area_m2 ({item.max_area_m2})"

        if item.min_width_m is not None:
            largest_side = max(footprint.width_m, footprint.depth_m)
            if item.min_width_m > largest_side + _EPSILON:
                return (
                    f"{item.room_type}: min_width_m ({item.min_width_m}) exceeds both footprint "
                    f"dimensions ({footprint.width_m}x{footprint.depth_m} m) — cannot fit at any orientation"
                )

    known_room_types = {item.room_type for item in spec.program}
    referenced_room_types = {spec.circulation.entry_room_type} if spec.circulation is not None else set()
    for zone in spec.zones:
        referenced_room_types.update(zone.room_types)
    for rel in spec.relationships:
        referenced_room_types.add(rel.room_type_a)
        referenced_room_types.add(rel.room_type_b)
    # Redundant with ArchitecturalSpec's own cross-reference validator — same defense-in-depth
    # rationale as the area check above.
    missing = sorted(referenced_room_types - known_room_types)
    if missing:
        return f"room type(s) referenced but missing from program: {missing}"

    return None


def _attachment_positions(
    placed_partners: list[RoomInstance], width: float, height: float
) -> set[tuple[float, float]]:
    """Extra candidate positions that put a shape flush against a REQUIRED partner on any of its
    four sides, at both alignments -- used only when `required_edges` is given (concept-first
    planning). The legacy `_candidate_positions` only offers a placed room's bottom-right corner
    anchors, which cannot realize a planned edge to a partner's left/top side or a second partner
    on the same side; these anchors let geometry REALIZE a planned adjacency rather than stumble
    on it."""
    positions: set[tuple[float, float]] = set()
    for p in placed_partners:
        right, bottom = p.x + p.width, p.y + p.height
        for x in (right, p.x - width):                       # right of / left of partner
            for y in (p.y, bottom - height):                 # top-aligned / bottom-aligned
                positions.add((round(x, 6), round(y, 6)))
        for y in (bottom, p.y - height):                     # below / above partner
            for x in (p.x, right - width):                   # left-aligned / right-aligned
                positions.add((round(x, 6), round(y, 6)))
    return positions


def generate_valid_candidate_pool(
    spec: ArchitecturalSpec, footprint: BuildingFootprintSpec, required_edges=None
) -> list[list[RoomInstance]]:
    """Every complete, ALL-HARD-CONSTRAINTS-SATISFIED layout the backtracking search finds across
    every instance-order strategy (see `_INSTANCE_ORDER_STRATEGIES`), deduped by signature — the
    exact same pool `GeometrySolver.solve()` itself ranks over. Extracted as its own function
    (Spatial V2 integration) so a caller other than `solve()` can reuse this identical,
    unmodified hard-feasibility search and apply its own ranking/selection on top, without
    duplicating any backtracking, shape-candidate, position-candidate, or hard-constraint logic.
    `solve()` below calls this function; its own behavior is unchanged by this extraction.

    `required_edges` (concept-first planning, app.geometry.planning): an optional sequence of
    objects with `.a`, `.b` (instance ids) and `.min_shared_wall_m`. When given, each edge is a
    HARD constraint: a placement whose required partner is already placed is pruned unless the two
    share at least that much wall, extra flush-against-partner anchors are tried
    (`_attachment_positions`), and a complete layout is only kept if every edge holds. When `None`
    (the default, and every pre-existing caller), the search is byte-for-byte the legacy one.

    Does NOT run `_find_pre_solver_contradiction` -- callers that want that cheap pre-check
    (as `solve()` does) must call it themselves first.
    """
    instances = expand_program_to_instances(spec.program)

    partners_of: dict[str, list[tuple[str, float]]] = {}
    for edge in required_edges or ():
        partners_of.setdefault(edge.a, []).append((edge.b, edge.min_shared_wall_m))
        partners_of.setdefault(edge.b, []).append((edge.a, edge.min_shared_wall_m))

    def _required_edges_hold(placed_rooms: list[RoomInstance]) -> bool:
        by_id = {room.id: room for room in placed_rooms}
        for edge in required_edges or ():
            a, b = by_id.get(edge.a), by_id.get(edge.b)
            if a is None or b is None or _shared_edge_length(a, b) + _EPSILON < edge.min_shared_wall_m:
                return False
        return True

    # Step 3: run the search once per order strategy (see `_INSTANCE_ORDER_STRATEGIES`) and pool
    # every complete valid layout found across all passes — this is what gives ranking real
    # candidates to choose among, instead of near-duplicates of a single fixed traversal. Hard
    # constraints, overlap/bounds checks, and the shape/position candidate generation are completely
    # unchanged from before this milestone; only WHICH ORDER instances are attempted in varies.
    solutions: list[list[RoomInstance]] = []
    seen_signatures: set[tuple] = set()

    for strategy in _INSTANCE_ORDER_STRATEGIES:
        ordered = _order_instances(spec, instances, strategy)
        # ROOM_INSTANCE_SIZE_FIDELITY: `item` here is THIS instance's own originating ProgramItem
        # (from `ordered`'s tuple, never a `{room_type: item}` re-lookup) -- two same-type
        # instances from different ProgramItems (e.g. differently-sized bedrooms) each get shape
        # candidates from their OWN target/min/max area, not whichever item a type-keyed dict
        # happened to keep.
        pending = [
            _PendingInstance(
                id=instance_id, type=room_type, candidate_shapes=_candidate_shapes(item)
            )
            for instance_id, room_type, item in ordered
        ]

        pass_solutions: list[list[RoomInstance]] = []
        steps = 0

        def backtrack(index: int, placed: list[RoomInstance]) -> None:
            nonlocal steps
            if len(pass_solutions) >= _MAX_SOLUTIONS or steps >= _MAX_BACKTRACK_STEPS:
                return

            if index == len(pending):
                if _layout_satisfies_hard_requirements(spec, footprint, placed) and _required_edges_hold(placed):
                    pass_solutions.append(list(placed))
                return

            current = pending[index]
            # Concept-first planning: required partners already placed drive extra anchors and prune.
            placed_by_id = {p.id: p for p in placed}
            required_partners = [
                (placed_by_id[pid], min_wall) for pid, min_wall in partners_of.get(current.id, ()) if pid in placed_by_id
            ]
            for width, height in current.candidate_shapes:
                anchors = _candidate_positions(placed, footprint, width, height)
                if required_partners:
                    anchors = sorted(set(anchors) | _attachment_positions([p for p, _w in required_partners], width, height))
                for x, y in anchors:
                    steps += 1
                    if steps >= _MAX_BACKTRACK_STEPS:
                        return
                    if x < -_EPSILON or y < -_EPSILON:
                        continue
                    if x + width > footprint.width_m + _EPSILON or y + height > footprint.depth_m + _EPSILON:
                        continue
                    if any(_overlaps(x, y, width, height, p.x, p.y, p.width, p.height) for p in placed):
                        continue

                    candidate_room = RoomInstance(
                        id=current.id,
                        type=current.type,
                        floor=footprint.floor,
                        x=x,
                        y=y,
                        width=width,
                        height=height,
                        area_m2=round(width * height, 2),
                    )
                    if any(
                        _shared_edge_length(candidate_room, partner) + _EPSILON < min_wall
                        for partner, min_wall in required_partners
                    ):
                        continue  # planned edge would not be realized here -- prune, never relax

                    placed.append(candidate_room)
                    backtrack(index + 1, placed)
                    placed.pop()

                    if len(pass_solutions) >= _MAX_SOLUTIONS:
                        return

        backtrack(0, [])

        for solution in pass_solutions:
            signature = tuple(
                sorted((room.type, round(room.x, 3), round(room.y, 3), round(room.width, 3), round(room.height, 3)) for room in solution)
            )
            if signature in seen_signatures:
                continue
            seen_signatures.add(signature)
            solutions.append(solution)

    return solutions


class GeometrySolver:
    def solve(self, spec: ArchitecturalSpec, footprint: BuildingFootprintSpec) -> GeometrySolverResult:
        contradiction = _find_pre_solver_contradiction(spec, footprint)
        if contradiction is not None:
            return GeometrySolverResult(status=SolverStatus.unsatisfiable, unsatisfiable_reason=contradiction)

        instances = expand_program_to_instances(spec.program)
        solutions = generate_valid_candidate_pool(spec, footprint)

        if not solutions:
            return GeometrySolverResult(
                status=SolverStatus.unsatisfiable,
                unsatisfiable_reason=(
                    f"No layout satisfies every hard constraint within a {footprint.width_m:.1f}x"
                    f"{footprint.depth_m:.1f} m footprint (floor {footprint.floor}, "
                    f"{footprint.available_area_m2:.1f} m² available) for {len(instances)} room "
                    f"instance(s), within the search budget ({_MAX_BACKTRACK_STEPS} steps per ordering "
                    f"strategy, {len(_INSTANCE_ORDER_STRATEGIES)} strategies tried)"
                ),
            )

        scored = [(placement, *_score_candidate(spec, footprint, placement)) for placement in solutions]
        scored.sort(key=lambda entry: entry[1].total, reverse=True)
        best, best_breakdown, best_quality = scored[0]
        by_type = _group_by_type(best)

        soft_reports = _relationship_reports(spec, best, ConstraintSeverity.soft)
        soft_satisfied = [report for report in soft_reports if report.satisfied]
        soft_unsatisfied = [report for report in soft_reports if not report.satisfied]

        hard_checked = _relationship_reports(spec, best, ConstraintSeverity.hard) + [
            ConstraintCheckResult(
                description=(
                    f"total placed room area within the footprint's available area "
                    f"({footprint.available_area_m2:.1f} m²)"
                ),
                kind="available_area",
                severity=ConstraintSeverity.hard,
                satisfied=True,  # guaranteed by _layout_satisfies_hard_requirements above
            ),
        ]
        if spec.circulation is not None:
            hard_checked.append(
                ConstraintCheckResult(
                    description=(
                        f"entry room ({spec.circulation.entry_room_type}) touches an allowed entry edge "
                        f"({', '.join(edge.value for edge in _allowed_entry_edges(footprint))})"
                    ),
                    kind="entry_perimeter_access",
                    severity=ConstraintSeverity.hard,
                    satisfied=True,
                    note="V1 approximation: touching an allowed footprint edge, not a verified street/path approach",
                )
            )
        for zone in spec.zones:
            if zone.cohesion_severity == ConstraintSeverity.hard:
                hard_checked.append(
                    ConstraintCheckResult(
                        description=f"zone {zone.name!r} rooms form a single connected group",
                        kind="zone_cohesion",
                        severity=ConstraintSeverity.hard,
                        satisfied=True,
                    )
                )

        # Step 3: "explainable" candidate summaries — the top few pooled candidates' own breakdowns
        # (already computed above for ranking, not recomputed here), so a caller can see why the winner
        # beat the runners-up without re-running anything.
        candidate_summaries = [breakdown for _placement, breakdown, _quality in scored[:5]]

        return GeometrySolverResult(
            status=SolverStatus.satisfied,
            instances=best,
            hard_constraints_checked=hard_checked,
            soft_constraints_satisfied=soft_satisfied,
            soft_constraints_not_satisfied=soft_unsatisfied,
            zone_cohesion_score=best_breakdown.zone_cohesion_score,
            circulation_reach_score=best_breakdown.circulation_reach_score,
            objective_score=best_breakdown.total,
            quality=best_quality,
            objective_breakdown=best_breakdown,
            candidate_count=len(scored),
            candidate_summaries=candidate_summaries,
        )
